### ISSUE TITLE
Add thin, puma, webrick or other rack server gem to Gemfile

### ISSUE THREAD

**Issue by nfilzi** [lewagon/activerecord-sinatra-boilerplate#14]
Got an error running `bundle exec ruby app.rb` seconds before kickstarting the livecode 🥵

Ended running with one of the fixes mentioned in this [>SO thread<](https://stackoverflow.com/questions/67615800/ruby-sinatra-compile-error-server-handler-thin-puma-reel-http-webrick-not-fo)

**Comment by dmilon** [comment]
Hi @nfilzi :wave: Thank you for reporting :pray: Fixed by https://github.com/lewagon/activerecord-sinatra-boilerplate/commit/9bbc60cf3dcbcf5b57e778291f32822ba40c5ca7
